#!/usr/bin/env python3
"""Sweep Neural Cache quality using an existing high-sample Pure WoS reference.

This runner is intended for the stage after a fixed slice point set and a
high-sample Pure-WoS numerical reference have already been generated by
run_nc_slice_reference_time_to_mse.py.  It does NOT rebuild the reference.
Instead it reuses reference_pure_estimates.csv and compares multiple cache
training schedules / capacities against the same reference.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Tuple


def parse_list_int(text: str) -> List[int]:
    return [int(x) for x in text.split(',') if x.strip()]


def parse_list_str(text: str) -> List[str]:
    return [x.strip() for x in text.split(',') if x.strip()]


def parse_allocs(text: str) -> List[Tuple[int, int]]:
    out: List[Tuple[int, int]] = []
    for item in text.split(','):
        item = item.strip()
        if not item:
            continue
        a, b = item.split(':')
        out.append((int(a), int(b)))
    return out


def parse_list_float(text: str) -> List[float]:
    return [float(x) for x in text.split(',') if x.strip()]


def run(cmd: List[str], dry_run: bool) -> None:
    print('+', ' '.join(cmd), flush=True)
    if not dry_run:
        subprocess.run(cmd, check=True)


def read_json(path: Path) -> Dict[str, Any]:
    with path.open('r', encoding='utf-8') as f:
        return json.load(f)


def read_estimates(path: Path) -> List[Dict[str, str]]:
    with path.open('r', encoding='utf-8', newline='') as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: List[Dict[str, Any]], fields: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction='ignore')
        w.writeheader()
        for row in rows:
            w.writerow(row)


def load_reference(path: Path) -> Tuple[List[float], List[float], int, int]:
    rows = read_estimates(path)
    if not rows:
        raise RuntimeError(f'empty reference estimates: {path}')
    means: List[float] = []
    vars_: List[float] = []
    reference_wpp = 0
    for i, row in enumerate(rows):
        if 'pure_mean' not in row:
            raise RuntimeError(f'reference row {i} has no pure_mean column: {path}')
        means.append(float(row['pure_mean']))
        vars_.append(float(row.get('pure_sample_variance', 0.0)))
        if i == 0 and row.get('reference_wpp'):
            try:
                reference_wpp = int(float(row['reference_wpp']))
            except ValueError:
                reference_wpp = 0
    return means, vars_, len(rows), reference_wpp


def mse_vs_reference(rows: List[Dict[str, str]], ref: List[float], column: str) -> Tuple[float, float, float, float, float]:
    if len(rows) != len(ref):
        raise RuntimeError(f'row count mismatch for {column}: {len(rows)} vs reference {len(ref)}')
    mse = 0.0
    mae = 0.0
    max_abs = 0.0
    mean_err = 0.0
    for row, r in zip(rows, ref):
        if column not in row:
            raise RuntimeError(f'estimates CSV does not contain column {column}')
        e = float(row[column]) - r
        mse += e * e
        ae = abs(e)
        mae += ae
        max_abs = max(max_abs, ae)
        mean_err += e
    n = float(len(ref))
    mse /= n
    return mse, math.sqrt(max(0.0, mse)), mae / n, max_abs, mean_err / n


def get_node(root: Dict[str, Any], path: Tuple[str, ...]) -> Dict[str, Any]:
    node: Any = root
    for key in path:
        node = node[key]
    if not isinstance(node, dict):
        raise RuntimeError(f'JSON path {path} did not resolve to an object')
    return node


def main() -> int:
    ap = argparse.ArgumentParser(description='Sweep cache quality using a fixed numerical reference CSV.')
    ap.add_argument('--executable', required=True)
    ap.add_argument('--reference-estimates-csv', required=True)
    ap.add_argument('--output-dir', required=True)
    ap.add_argument('--mesh', default='procedural_bumpy_sphere')
    ap.add_argument('--mesh-path', default='')
    ap.add_argument('--normalize', type=int, default=1)
    ap.add_argument('--bumpy-stacks', type=int, default=128)
    ap.add_argument('--bumpy-slices', type=int, default=256)
    ap.add_argument('--bumpy-amplitude', type=float, default=0.15)
    ap.add_argument('--boundary', default='boundary_texture_stripes_k16')
    ap.add_argument('--label-source', default='wos_supervision')
    ap.add_argument('--cache-presets', default='nano,light,baseline')
    ap.add_argument('--train-points-list', default='20000')
    ap.add_argument('--train-sampler', default='rejection')
    ap.add_argument('--train-steps-per-refresh-list', default='5000')
    ap.add_argument('--label-refreshes', type=int, default=4)
    ap.add_argument('--walks-per-label-refresh', type=int, default=50)
    ap.add_argument('--depth-m', type=int, default=4)
    ap.add_argument('--eval-mode', choices=['slice'], default='slice')
    ap.add_argument('--slice-width', type=int, default=512)
    ap.add_argument('--slice-height', type=int, default=512)
    ap.add_argument('--slice-view', default='xy')
    ap.add_argument('--slice-plane', default='0')
    ap.add_argument('--slice-padding-fraction', default='0.02')
    ap.add_argument('--slice-preserve-world-aspect', type=int, default=1)
    ap.add_argument('--pure-walks-per-point', type=int, default=1, help='kept small; pure result from these runs is ignored')
    ap.add_argument('--hybrid-wpp-list', default='4,8,16')
    ap.add_argument('--lmc-allocations', default='16:8,32:16,32:32,64:32')
    ap.add_argument('--threshold-rmse-list', default='0.03,0.05,0.075,0.1')
    ap.add_argument('--max-steps', type=int, default=256)
    ap.add_argument('--epsilon', default='1e-4')
    ap.add_argument('--seed', type=int, default=12345)
    ap.add_argument('--seed-stride', type=int, default=1000003)
    ap.add_argument('--cubql-build-method', default='sah')
    ap.add_argument('--cubql-leaf-size', type=int, default=8)
    ap.add_argument('--jit', type=int, default=0)
    ap.add_argument('--dry-run', action='store_true')
    ap.add_argument('--skip-existing', action='store_true')
    args = ap.parse_args()

    out_dir = Path(args.output_dir)
    runs_dir = out_dir / 'runs'
    estimates_dir = out_dir / 'estimates'
    out_dir.mkdir(parents=True, exist_ok=True)
    runs_dir.mkdir(parents=True, exist_ok=True)
    estimates_dir.mkdir(parents=True, exist_ok=True)

    ref_csv = Path(args.reference_estimates_csv)
    if args.dry_run:
        ref_values: List[float] = []
        ref_vars: List[float] = []
        ref_count = 0
        reference_wpp = 0
        reference_rmse_floor = 0.0
    else:
        ref_values, ref_vars, ref_count, reference_wpp = load_reference(ref_csv)
        mean_ref_var = sum(ref_vars) / float(len(ref_vars)) if ref_vars else 0.0
        reference_rmse_floor = math.sqrt(max(0.0, mean_ref_var / float(max(1, reference_wpp)))) if reference_wpp > 0 else 0.0

    common = [
        args.executable,
        '--mesh', args.mesh,
        '--boundary', args.boundary,
        '--label-source', args.label_source,
        '--train-sampler', args.train_sampler,
        '--eval-mode', 'slice',
        '--slice-width', str(args.slice_width),
        '--slice-height', str(args.slice_height),
        '--slice-view', args.slice_view,
        '--slice-plane', str(args.slice_plane),
        '--slice-preserve-world-aspect', str(args.slice_preserve_world_aspect),
        '--slice-padding-fraction', str(args.slice_padding_fraction),
        '--depth-m', str(args.depth_m),
        '--max-steps', str(args.max_steps),
        '--epsilon', str(args.epsilon),
        '--cubql-build-method', args.cubql_build_method,
        '--cubql-leaf-size', str(args.cubql_leaf_size),
        '--normalize', str(args.normalize),
        '--jit', str(args.jit),
        '--bumpy-stacks', str(args.bumpy_stacks),
        '--bumpy-slices', str(args.bumpy_slices),
        '--bumpy-amplitude', str(args.bumpy_amplitude),
    ]
    if args.mesh_path:
        common += ['--mesh-path', args.mesh_path]

    cache_presets = parse_list_str(args.cache_presets)
    train_points_list = parse_list_int(args.train_points_list)
    train_steps_list = parse_list_int(args.train_steps_per_refresh_list)
    hybrid_wpp_list = parse_list_int(args.hybrid_wpp_list)
    allocations = parse_allocs(args.lmc_allocations)

    points: List[Dict[str, Any]] = []
    commands: List[Dict[str, Any]] = []

    def add_point(method: str, label: str, json_path: Path, prefix: Path, value_column: str, time_path: Tuple[str, ...], training_included: bool, meta: Dict[str, Any]) -> None:
        j = read_json(json_path)
        rows = read_estimates(Path(str(prefix) + '_estimates.csv'))
        mse, rmse, mae, max_abs, mean_error = mse_vs_reference(rows, ref_values, value_column)
        node = get_node(j, time_path)
        solve_ms = float(node.get('elapsed_ms', 0.0))
        training_ms = float(j.get('training', {}).get('total_training_ms', 0.0))
        total_ms = solve_ms + training_ms if training_included else solve_ms
        out = {
            'method': method,
            'label': label,
            'rmse_vs_reference': rmse,
            'mse_vs_reference': mse,
            'mae_vs_reference': mae,
            'max_abs_error_vs_reference': max_abs,
            'mean_error_vs_reference': mean_error,
            'solve_only_ms': solve_ms,
            'training_ms': training_ms,
            'training_plus_solve_ms': solve_ms + training_ms,
            'default_time_ms': total_ms,
            'reference_wpp': reference_wpp,
            'reference_rmse_floor_estimate': reference_rmse_floor,
            'json_path': str(json_path),
            'estimates_csv': str(prefix) + '_estimates.csv',
        }
        out.update(meta)
        # Helpful method-specific diagnostics.
        if method == 'nc_2lmc':
            node2 = get_node(j, ('runs', 'nc_2lmc'))
            pure_var = float(get_node(j, ('runs', 'pure_wos')).get('mean_sample_variance', 0.0))
            residual_var = float(node2.get('mean_residual_sample_variance', 0.0))
            out['mean_residual_sample_variance'] = residual_var
            out['residual_variance_ratio_vs_run_pure'] = residual_var / pure_var if pure_var > 0.0 else ''
        if method == 'nc_wos':
            node2 = get_node(j, ('runs', 'nc_wos'))
            out['nc_wos_mean_sample_variance'] = node2.get('mean_sample_variance', '')
        points.append(out)

    for cache_preset in cache_presets:
        for train_points in train_points_list:
            for steps_per_refresh in train_steps_list:
                base_meta = {
                    'cache_preset': cache_preset,
                    'train_points': train_points,
                    'train_steps_per_refresh': steps_per_refresh,
                    'total_train_steps': steps_per_refresh * args.label_refreshes,
                    'label_refreshes': args.label_refreshes,
                    'walks_per_label_refresh': args.walks_per_label_refresh,
                    'depth_m': args.depth_m,
                    'boundary': args.boundary,
                }

                # NC-only budgets.
                for wpp in hybrid_wpp_list:
                    label = f'{cache_preset}_tp{train_points}_s{steps_per_refresh}_nc_wpp{wpp}'
                    json_path = runs_dir / f'{label}.json'
                    prefix = estimates_dir / label
                    cmd = common + [
                        '--cache-preset', cache_preset,
                        '--train-points', str(train_points),
                        '--label-refreshes', str(args.label_refreshes),
                        '--walks-per-label-refresh', str(args.walks_per_label_refresh),
                        '--train-steps-per-refresh', str(steps_per_refresh),
                        '--pure-walks-per-point', str(args.pure_walks_per_point),
                        '--hybrid-walks-per-point', str(wpp),
                        '--enable-2lmc', '0',
                        '--coarse-walks-per-point', '1',
                        '--residual-walks-per-point', '1',
                        '--seed', str(args.seed + args.seed_stride + wpp + 17 * train_points + 101 * steps_per_refresh),
                        '--slice-output-prefix', str(out_dir / 'slice'),
                        '--save-estimates-prefix', str(prefix),
                        '--output', str(json_path),
                    ]
                    commands.append({'method': 'nc_wos', 'label': label, 'command': cmd})
                    if not (args.skip_existing and json_path.exists() and Path(str(prefix) + '_estimates.csv').exists()):
                        run(cmd, args.dry_run)
                    if not args.dry_run:
                        meta = dict(base_meta)
                        meta.update({'hybrid_wpp': wpp, 'coarse_wpp': '', 'residual_wpp': ''})
                        add_point('nc_wos', label, json_path, prefix, 'nc_wos_mean', ('runs', 'nc_wos'), True, meta)

                # NC+2LMC allocations.
                for coarse, residual in allocations:
                    label = f'{cache_preset}_tp{train_points}_s{steps_per_refresh}_nc2lmc_c{coarse}_r{residual}'
                    json_path = runs_dir / f'{label}.json'
                    prefix = estimates_dir / label
                    cmd = common + [
                        '--cache-preset', cache_preset,
                        '--train-points', str(train_points),
                        '--label-refreshes', str(args.label_refreshes),
                        '--walks-per-label-refresh', str(args.walks_per_label_refresh),
                        '--train-steps-per-refresh', str(steps_per_refresh),
                        '--pure-walks-per-point', str(args.pure_walks_per_point),
                        '--hybrid-walks-per-point', '1',
                        '--enable-2lmc', '1',
                        '--coarse-walks-per-point', str(coarse),
                        '--residual-walks-per-point', str(residual),
                        '--seed', str(args.seed + 2 * args.seed_stride + 31 * coarse + 37 * residual + 17 * train_points + 101 * steps_per_refresh),
                        '--slice-output-prefix', str(out_dir / 'slice'),
                        '--save-estimates-prefix', str(prefix),
                        '--output', str(json_path),
                    ]
                    commands.append({'method': 'nc_2lmc', 'label': label, 'command': cmd})
                    if not (args.skip_existing and json_path.exists() and Path(str(prefix) + '_estimates.csv').exists()):
                        run(cmd, args.dry_run)
                    if not args.dry_run:
                        meta = dict(base_meta)
                        meta.update({'hybrid_wpp': '', 'coarse_wpp': coarse, 'residual_wpp': residual})
                        add_point('nc_2lmc', label, json_path, prefix, 'nc_2lmc_mean', ('runs', 'nc_2lmc'), True, meta)

    manifest = {
        'schema': 'n2wos_reference_cache_quality_sweep_v1',
        'arguments': vars(args),
        'reference': {
            'estimates_csv': str(ref_csv),
            'point_count': ref_count,
            'reference_wpp_from_csv': reference_wpp,
            'reference_rmse_floor_estimate': reference_rmse_floor,
        },
        'commands': commands,
        'limitations': {
            'fixed_reference_reused': True,
            'does_not_build_reference': True,
            'method_runs_train_cache_independently': True,
            'pure_wos_in_each_executable_is_minimized_and_ignored': True,
            'not_true_online_progressive_runner': True,
        },
    }
    (out_dir / 'manifest.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')

    if args.dry_run:
        return 0

    fields = [
        'method','label','cache_preset','train_points','train_steps_per_refresh','total_train_steps',
        'label_refreshes','walks_per_label_refresh','depth_m','boundary','hybrid_wpp','coarse_wpp','residual_wpp',
        'rmse_vs_reference','mse_vs_reference','mae_vs_reference','max_abs_error_vs_reference','mean_error_vs_reference',
        'solve_only_ms','training_ms','training_plus_solve_ms','default_time_ms',
        'reference_wpp','reference_rmse_floor_estimate','mean_residual_sample_variance','residual_variance_ratio_vs_run_pure','nc_wos_mean_sample_variance',
        'json_path','estimates_csv'
    ]
    write_csv(out_dir / 'cache_quality_time_mse_points_reference.csv', points, fields)

    # Time-to-threshold table for the cache-quality sweep.
    threshold_rows: List[Dict[str, Any]] = []
    for thr in parse_list_float(args.threshold_rmse_list):
        for method in ['nc_wos', 'nc_2lmc']:
            candidates = [p for p in points if p['method'] == method and p['rmse_vs_reference'] <= thr]
            for time_mode in ['solve_only_ms', 'training_plus_solve_ms']:
                if candidates:
                    best = min(candidates, key=lambda p: float(p[time_mode]))
                    threshold_rows.append({
                        'threshold_rmse': thr,
                        'method': method,
                        'time_mode': time_mode,
                        'hit': True,
                        'best_time_ms': best[time_mode],
                        'best_label': best['label'],
                        'best_rmse_vs_reference': best['rmse_vs_reference'],
                        'cache_preset': best['cache_preset'],
                        'train_points': best['train_points'],
                        'train_steps_per_refresh': best['train_steps_per_refresh'],
                        'coarse_wpp': best.get('coarse_wpp', ''),
                        'residual_wpp': best.get('residual_wpp', ''),
                        'hybrid_wpp': best.get('hybrid_wpp', ''),
                    })
                else:
                    threshold_rows.append({
                        'threshold_rmse': thr,
                        'method': method,
                        'time_mode': time_mode,
                        'hit': False,
                        'best_time_ms': '',
                        'best_label': '',
                        'best_rmse_vs_reference': '',
                        'cache_preset': '',
                        'train_points': '',
                        'train_steps_per_refresh': '',
                        'coarse_wpp': '',
                        'residual_wpp': '',
                        'hybrid_wpp': '',
                    })
    write_csv(out_dir / 'cache_quality_time_to_threshold_reference.csv', threshold_rows, ['threshold_rmse','method','time_mode','hit','best_time_ms','best_label','best_rmse_vs_reference','cache_preset','train_points','train_steps_per_refresh','coarse_wpp','residual_wpp','hybrid_wpp'])

    summary = dict(manifest)
    summary['points'] = points
    summary['thresholds'] = threshold_rows
    (out_dir / 'summary_reference_cache_quality.json').write_text(json.dumps(summary, indent=2), encoding='utf-8')
    print('wrote', out_dir / 'cache_quality_time_mse_points_reference.csv')
    print('wrote', out_dir / 'cache_quality_time_to_threshold_reference.csv')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
